### PR TITLE
Fix MoeIDE conflict

### LINKED ISSUE #137: Weird conflict with the MoeIde extension
image
The background becomes transparent, making it unreadable, and you can see a kind of mini version of the editor window in background nesting another mini version of the editor
https://github.com/Meowtrix/MoeIDE

### PR DESCRIPTION
**Pull request by sylveon**
Fixes #137

### CODE REVIEW

File: GitDiffMargin/View/OpaqueColorConverter.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+            var newBrush = ((Brush)value).Clone();
+            newBrush.Opacity = 1.0; // Remove transparency
+
+            return newBrush;
+        }
+
+        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
+        {
+            // We don't need to convert back. What should we do anyways? We don't know the original opacity, nor we can we get it.
+            throw new NotSupportedException();
```
Comment (sharwell) [inline GitDiffMargin/View/OpaqueColorConverter.cs]: ❗️ Return `DependencyProperty.UnsetValue` rather than throw an exception. For more information, see the section on [Exceptions from converters](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.ivalueconverter.convert#exceptions-from-converters).

Comment (sylveon) [reply GitDiffMargin/View/OpaqueColorConverter.cs]: @sharwell @laurentkempe Thanks, done. I don't do WPF that often (although I wish I could more)

**Comment by laurentkempe** [comment]
Thx for the fix @sylveon
