### PR TITLE
Detect CPS opening project files from temporary locations

### LINKED ISSUE #129: Diff margin not shown when editing a project file
**Steps to reproduce:**

1. In Visual Studio 2017, create a new project with the .NET SDK (or open an existing one such as the projects in [Microsoft/vs-threading](https://github.com/Microsoft/vs-threading/))
2. *Without unloading the project first*, right click on the project in **Solution Explorer** and select **Edit [Project file name]**

**Expected behavior:**

The diff margin is shown if the project is in a Git source control store.

**Actual behavior:**

The diff margin is not shown.

**Additional details:**

The command described above creates a temporary file with the contents of the original project file on disk, and opens the temporary file instead of the original. GitDiffMargin doesn't know how to associate that temporary location back to the original location in the solution.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #129 

:memo: Thanks to @333fred for suggestions regarding the approach.

### CODE REVIEW

File: GitDiffMargin/Git/GitCommands.cs [hunk 1]
```diff
@@ -207,7 +213,7 @@ public void StartExternalDiff(ITextDocument textDocument)
                     leftLabel = string.Format("{0}@{1}", objectName, repo.Head.Tip.Sha.Substring(0, 7));
                 }
 
-                string rightLabel = filename;
+                string rightLabel = originalPath;
```
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: :memo: This one is clever. It makes the diff window *look* like the original file is being edited, even though the buffer still maps to the temporary location.

File: GitDiffMargin/Git/GitCommands.cs [hunk 2]
```diff
@@ -282,5 +325,90 @@ static bool HasPreamble(string file, Encoding encoding)
...
+                return fullPath;
+
+            if (!ErrorHandler.Succeeded(solution.GetProjectEnum((uint)__VSENUMPROJFLAGS.EPF_LOADEDINSOLUTION, Guid.Empty, out IEnumHierarchies ppenum))
+                || ppenum == null)
+            {
+                return fullPath;
+            }
+
+            List<string> projectFiles = new List<string>();
+            IVsHierarchy[] hierarchies = new IVsHierarchy[1];
```
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: I doubt there are guaranteed to be 2 hierarchies, especially  if it's a solution with no projects.

File: GitDiffMargin/Git/GitCommands.cs [hunk 3]
```diff
@@ -282,5 +325,90 @@ static bool HasPreamble(string file, Encoding encoding)
...
+
+                for (uint i = 0; i < fetched; i++)
+                {
+                    if (!(hierarchies[0] is IVsProject project))
+                        continue;
+
+                    if (!ErrorHandler.Succeeded(project.GetMkDocument((uint)VSConstants.VSITEMID.Root, out string projectFilePath)))
+                        continue;
+
+                    if (!Path.GetFileName(projectFilePath).Equals(Path.GetFileName(fullPath), StringComparison.OrdinalIgnoreCase))
```
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: No need to use OrdinalIgnoreCase, if they're not the same case they're not the same file. I used the original case when I created the temp file.

File: GitDiffMargin/Git/GitCommands.cs [hunk 4]
```diff
@@ -282,5 +325,90 @@ static bool HasPreamble(string file, Encoding encoding)
...
+            case 1:
+                // Exactly one matching project file found in solution
+                return projectFiles[0];
+
+            default:
+                // Multiple project files found in solution; try to find one with a matching file size
+                long desiredSize = new FileInfo(fullPath).Length;
+                foreach (var projectFilePath in projectFiles)
+                {
+                    if (File.Exists(projectFilePath) && new FileInfo(projectFilePath).Length == desiredSize)
```
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: Note that there are technically races here, as there are very brief windows of time where the two files are not synchronized. However, these are very brief.

Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: @sharwell, can you please test the following case:
1. Create a new net core app. 
2. Add a reference via the package management console. 
3. Open the csproj without saving anything.

File: GitDiffMargin/Git/GitCommands.cs [hunk 5]
```diff
@@ -282,5 +325,90 @@ static bool HasPreamble(string file, Encoding encoding)
 
             return true;
         }
+
+        private string AdjustPath(string fullPath)
+        {
+            // Right now the only extension is for *.csproj and *.vbproj, which are opened from a temporary location
+            switch (Path.GetExtension(fullPath).ToLowerInvariant())
```
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: Oh, and shared projects, which I believe is shproj?

Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: A better approach is probably to first see if it ends in just `proj`, and then do the comparison with project file names.

File: GitDiffMargin/Git/GitCommands.cs [hunk 6]
```diff
@@ -282,5 +325,90 @@ static bool HasPreamble(string file, Encoding encoding)
...
+                    if (!(hierarchies[0] is IVsProject project))
+                        continue;
+
+                    if (!ErrorHandler.Succeeded(project.GetMkDocument((uint)VSConstants.VSITEMID.Root, out string projectFilePath)))
+                        continue;
+
+                    if (!Path.GetFileName(projectFilePath).Equals(Path.GetFileName(fullPath), StringComparison.OrdinalIgnoreCase))
+                        continue;
+
+                    projectFiles.Add(projectFilePath);
```
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: An additional check you can do that's pretty cheap is check to see if the project has the `OpenProjectFile` capability.

File: GitDiffMargin/Git/GitCommands.cs (hunk 2 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: :arrow_right: This array is used to return the results from a COM enumerator. The size of 1 means we enumerate the items 1 at a time, which is the easiest to deal with.

File: GitDiffMargin/Git/GitCommands.cs (hunk 3 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: I originally used `IVsHierarchy.GetCanonicalName`. Once I switched to `GetMkDocument` this is correct. I'll update the code to use `Ordinal` instead.

File: GitDiffMargin/Git/GitCommands.cs (hunk 4 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: In reality this method is called only once per document, in a callback to user code during the call to [`OpenDocumentWithSpecificEditor`](https://github.com/dotnet/project-system/blob/2fe39a1106da2bfe346a2166b501dadd70d86f8e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/VsShellUtilitiesHelper.cs#L37). It would be unlikely for the files to be out of sync. Also, this code only runs in the case where the solution has two or more projects with the same name *and* the file being opened is one of those duplicates.

File: GitDiffMargin/Git/GitCommands.cs (hunk 6 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: How would this check be done? I'm not sure we're able to reference the necessary assemblies from this project considering it supports several versions of Visual Studio.

File: GitDiffMargin/Git/GitCommands.cs (hunk 4 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: > can you please test the following case

The detection of the original file path worked fine here, but the `IsDirty` check failed, resulting in an empty diff. I corrected this as its own commit in the branch. 👍

File: GitDiffMargin/Git/GitCommands.cs (hunk 3 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: ➡️ Fixed

File: GitDiffMargin/Git/GitCommands.cs (hunk 5 above)
Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: :arrow_right: Fixed

File: GitDiffMargin/Git/GitCommands.cs (hunk 6 above)
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: @sharwell, you can use https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivshierarchy.getproperty.aspx, with `__VSHPROPID5.VSHPROPID_ProjectCapabilities`. https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.__vshpropid5.aspx

Comment (sharwell) [inline GitDiffMargin/Git/GitCommands.cs]: :memo: @333fred linked me to this separately: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs

File: GitDiffMargin/Git/GitCommands.cs (hunk 2 above)
Comment (333fred) [inline GitDiffMargin/Git/GitCommands.cs]: That's what I get for reviewing on my phone :).

**Comment by laurentkempe** [comment]
Thanks @sharwell and @333fred for the pull request and the fix!
